=== desam/organizer/schemas/events.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT events (event+)>

<!ELEMENT event (title, from, to, location, guest*)>
<!ATTLIST event
  id ID #REQUIRED
  refgrp CDATA #REQUIRED
>

<!ELEMENT title (#PCDATA)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT to (#PCDATA)>
<!ELEMENT location (#PCDATA)>
<!ELEMENT guest EMPTY>
<!ATTLIST guest
  refuser CDATA #REQUIRED
>

=== desam/organizer/schemas/events.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE events SYSTEM "events.dtd" >
<events>
    <event refgrp="1">
      <from>2010-09-23 09:00</from>
      <to>2010-09-23 12:00</to>
      <location>location2</location>
    </event>

    <event refgrp="2">
      <from>2010-09-23 14:00</from>
      <to>2010-09-23 17:00</to>
      <location>location2</location>
    </event>

    <event refgrp="1">
      <from>2010-09-24 09:00</from>
      <to>2010-09-24 12:00</to>
      <location>location1</location>
    </event>

    <event refgrp="1">
      <from>2010-09-24 14:00</from>
      <to>2010-09-24 17:00</to>
      <location>location1</location>
    </event>

    <event refgrp="1">
      <from>2010-09-25 09:00</from>
      <to>2010-09-25 12:00</to>
      <location>location2</location>
    </event>

    <event refgrp="1">
      <from>2010-09-25 14:00</from>
      <to>2010-09-25 17:00</to>
      <location>location2</location>
      <guest refuser="19" />
      <guest refuser="28" />
    </event>

    <event refgrp="2">
      <from>2010-09-26 09:00</from>
      <to>2010-09-26 12:00</to>
      <location>location2</location>
    </event>

    <event refgrp="2">
      <from>2010-09-26 14:00</from>
      <to>2010-09-26 17:00</to>
      <location>location0</location>
    </event>

    <event refgrp="2">
      <from>2010-09-27 09:00</from>
      <to>2010-09-27 12:00</to>
      <location>location0</location>
    </event>

    <event refgrp="2">
      <from>2010-09-27 14:00</from>
      <to>2010-09-27 17:00</to>
      <location>location1</location>
    </event>

    <event refgrp="2">
      <from>2010-09-28 09:00</from>
      <to>2010-09-28 12:00</to>
      <location>location1</location>
    </event>

    <event refgrp="1">
      <from>2010-09-28 14:00</from>
      <to>2010-09-28 17:00</to>
      <location>location1</location>
      <guest refuser="12" />
      <guest refuser="66" />
    </event>

    <event refgrp="2">
      <from>2010-09-29 09:00</from>
      <to>2010-09-29 12:00</to>
      <location>location0</location>
    </event>

    <event refgrp="1">
      <from>2010-09-29 14:00</from>
      <to>2010-09-29 17:00</to>
      <location>location0</location>
      <guest refuser="33" />
    </event>

    <event refgrp="1">
      <from>2010-09-30 09:00</from>
      <to>2010-09-30 12:00</to>
      <location>location2</location>
    </event>

    <event refgrp="1">
      <from>2010-09-30 14:00</from>
      <to>2010-09-30 17:00</to>
      <location>location2</location>
    </event>

    <event refgrp="1">
      <from>2010-10-01 09:00</from>
      <to>2010-10-01 12:00</to>
      <location>location0</location>
    </event>

    <event refgrp="2">
      <from>2010-10-01 14:00</from>
      <to>2010-10-01 17:00</to>
      <location>location0</location>
    </event>

    <event refgrp="2">
      <from>2010-10-02 09:00</from>
      <to>2010-10-02 12:00</to>
      <location>location1</location>
    </event>

    <event refgrp="1">
      <from>2010-10-02 14:00</from>
      <to>2010-10-02 17:00</to>
      <location>location2</location>
      <guest refuser="1" />
      <guest refuser="54" />
    </event>

    <event refgrp="2">
      <from>2010-10-03 09:00</from>
      <to>2010-10-03 12:00</to>
      <location>location2</location>
    </event>

    <event refgrp="2">
      <from>2010-10-03 14:00</from>
      <to>2010-10-03 17:00</to>
      <location>location2</location>
    </event>

    <event refgrp="1">
      <from>2010-10-04 09:00</from>
      <to>2010-10-04 12:00</to>
      <location>location0</location>
    </event>

    <event refgrp="2">
      <from>2010-10-04 14:00</from>
      <to>2010-10-04 17:00</to>
      <location>location2</location>
    </event>

    <event refgrp="2">
      <from>2010-10-05 09:00</from>
      <to>2010-10-05 12:00</to>
      <location>location0</location>
    </event>

    <event refgrp="2">
      <from>2010-10-05 14:00</from>
      <to>2010-10-05 17:00</to>
      <location>location0</location>
      <guest refuser="45" />
    </event>

    <event refgrp="2">
      <from>2010-10-06 09:00</from>
      <to>2010-10-06 12:00</to>
      <location>location1</location>
    </event>

    <event refgrp="2">
      <from>2010-10-06 14:00</from>
      <to>2010-10-06 17:00</to>
      <location>location2</location>
    </event>

    <event refgrp="1">
      <from>2010-10-07 09:00</from>
      <to>2010-10-07 12:00</to>
      <location>location2</location>
    </event>

    <event refgrp="2">
      <from>2010-10-07 14:00</from>
      <to>2010-10-07 17:00</to>
      <location>location0</location>
    </event>

    <event refgrp="2">
      <from>2010-10-08 09:00</from>
      <to>2010-10-08 12:00</to>
      <location>location2</location>
    </event>

    <event refgrp="2">
      <from>2010-10-08 14:00</from>
      <to>2010-10-08 17:00</to>
      <location>location0</location>
    </event>

    <event refgrp="2">
      <from>2010-10-09 09:00</from>
      <to>2010-10-09 12:00</to>
      <location>location0</location>
    </event>

    <event refgrp="2">
      <from>2010-10-09 14:00</from>
      <to>2010-10-09 17:00</to>
      <location>location0</location>
      <guest refuser="97" />
      <guest refuser="44" />
    </event>

    <event refgrp="1">
      <from>2010-10-10 09:00</from>
      <to>2010-10-10 12:00</to>
      <location>location0</location>
    </event>

    <event refgrp="2">
      <from>2010-10-10 14:00</from>
      <to>2010-10-10 17:00</to>
      <location>location1</location>
    </event>

    <event refgrp="2">
      <from>2010-10-11 09:00</from>
      <to>2010-10-11 12:00</to>
      <location>location0</location>
    </event>

    <event refgrp="1">
      <from>2010-10-11 14:00</from>
      <to>2010-10-11 17:00</to>
      <location>location2</location>
    </event>

    <event refgrp="2">
      <from>2010-10-12 09:00</from>
      <to>2010-10-12 12:00</to>
      <location>location0</location>
    </event>

    <event refgrp="2">
      <from>2010-10-12 14:00</from>
      <to>2010-10-12 17:00</to>
      <location>location1</location>
      <guest refuser="8" />
    </event>

    <event refgrp="1">
      <from>2010-10-13 09:00</from>
      <to>2010-10-13 12:00</to>
      <location>location1</location>
    </event>

    <event refgrp="1">
      <from>2010-10-13 14:00</from>
      <to>2010-10-13 17:00</to>
      <location>location1</location>
    </event>

    <event refgrp="2">
      <from>2010-10-14 09:00</from>
      <to>2010-10-14 12:00</to>
      <location>location2</location>
        <guest refuser="56" />
          <guest refuser="48" />
    </event>

    <event refgrp="2">
      <from>2010-10-14 14:00</from>
      <to>2010-10-14 17:00</to>
      <location>location0</location>
    </event>

    <event refgrp="2">
      <from>2010-10-15 09:00</from>
      <to>2010-10-15 12:00</to>
      <location>location0</location>
    </event>

    <event refgrp="2">
      <from>2010-10-15 14:00</from>
      <to>2010-10-15 17:00</to>
      <location>location0</location>
    </event>

    <event refgrp="1">
      <from>2010-10-16 09:00</from>
      <to>2010-10-16 12:00</to>
      <location>location1</location>
    </event>

    <event refgrp="2">
      <from>2010-10-16 14:00</from>
      <to>2010-10-16 17:00</to>
      <location>location1</location>
    </event>

    <event refgrp="1">
      <from>2010-10-17 09:00</from>
      <to>2010-10-17 12:00</to>
      <location>location1</location>
    </event>

    <event refgrp="1">
      <from>2010-10-17 14:00</from>
      <to>2010-10-17 17:00</to>
      <location>location0</location>
      <guest refuser="13" />
      <guest refuser="23" />
    </event>

    <event refgrp="1">
      <from>2010-10-18 09:00</from>
      <to>2010-10-18 12:00</to>
      <location>location0</location>
    </event>

    <event refgrp="2">
      <from>2010-10-18 14:00</from>
      <to>2010-10-18 17:00</to>
      <location>location1</location>
    </event>

    <event refgrp="2">
      <from>2010-10-19 09:00</from>
      <to>2010-10-19 12:00</to>
      <location>location0</location>
    </event>

    <event refgrp="2">
      <from>2010-10-19 14:00</from>
      <to>2010-10-19 17:00</to>
      <location>location1</location>
    </event>

    <event refgrp="1">
      <from>2010-10-20 09:00</from>
      <to>2010-10-20 12:00</to>
      <location>location1</location>
    </event>

    <event refgrp="2">
      <from>2010-10-20 14:00</from>
      <to>2010-10-20 17:00</to>
      <location>location1</location>
      <guest refuser="42" />
      <guest refuser="12" />
    </event>

    <event refgrp="1">
      <from>2010-10-21 09:00</from>
      <to>2010-10-21 12:00</to>
      <location>location0</location>
    </event>

    <event refgrp="1">
      <from>2010-10-21 14:00</from>
      <to>2010-10-21 17:00</to>
      <location>location0</location>
      <guest refuser="62" />
      <guest refuser="47" />
    </event>

    <event refgrp="1">
      <from>2010-10-22 09:00</from>
      <to>2010-10-22 12:00</to>
      <location>location1</location>
    </event>

    <event refgrp="2">
      <from>2010-10-22 14:00</from>
      <to>2010-10-22 17:00</to>
      <location>location2</location>
      <guest refuser="51" />
      <guest refuser="10" />
    </event>

    <event refgrp="2">
      <from>2010-10-23 09:00</from>
      <to>2010-10-23 12:00</to>
      <location>location0</location>
    </event>

    <event refgrp="2">
      <from>2010-10-23 14:00</from>
      <to>2010-10-23 17:00</to>
      <location>location2</location>
    </event>

    <event refgrp="1">
      <from>2010-10-24 09:00</from>
      <to>2010-10-24 12:00</to>
      <location>location0</location>
        <guest refuser="67" />
          <guest refuser="66" />
    </event>

    <event refgrp="1">
      <from>2010-10-24 14:00</from>
      <to>2010-10-24 17:00</to>
      <location>location2</location>
    </event>

    <event refgrp="1">
      <from>2010-10-25 09:00</from>
      <to>2010-10-25 12:00</to>
      <location>location0</location>
    </event>
