=== desam/organizer/schemas/groups.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT groups (group*)>

<!ELEMENT group (name, description, user*,avatar)>
<!ATTLIST group
  id ID #REQUIRED
>

<!ELEMENT name (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT user EMPTY>
<!ATTLIST user
          refuser CDATA #REQUIRED>
<!ELEMENT avatar (#PCDATA)>

=== desam/organizer/schemas/groups.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE groups SYSTEM "groups.dtd" >
<groups>
    <group id="1">
      <name>name1</name>
      <description>(1) honeymoon, n.:
	A short period of doting between dating and debting.
		-- Ray C. Bandy</description>
    </group>

    <group id="2">
      <name>name2</name>
      <description>(2) Has anyone ever tasted an "end"?  Are they really bitter?</description>
    </group>

    <group id="3">
      <name>name3</name>
      <description>(3) Most people have a furious itch to talk about themselves and are restrained
only by the disinclination of others to listen.  Reserve is an artificial
quality that is developed in most of us as the result of innumerable rebuffs.
		-- W.S. Maugham</description>
    </group>

    <group id="4">
      <name>name4</name>
      <description>(4) If the future isn't what it used to be, does that
mean that the past is subject to change in times to come?</description>
    </group>

    <group id="5">
      <name>name5</name>
      <description>(5) Given my druthers, I'd druther not.</description>
    </group>

    <group id="6">
      <name>name6</name>
      <description>(6) Galbraith's Law of Human Nature:
	Faced with the choice between changing one's mind and proving that
there is no need to do so, almost everybody gets busy on the proof.</description>
    </group>

    <group id="7">
      <name>name7</name>
      <description>(7) Either I'm dead or my watch has stopped.
		-- Groucho Marx's last words</description>
    </group>

    <group id="8">
      <name>name8</name>
      <description>(8) Q:	Why do the police always travel in threes?
A:	One to do the reading, one to do the writing, and the other keeps
	an eye on the two intellectuals.</description>
    </group>

    <group id="9">
      <name>name9</name>
      <description>(9) "They're unfriendly, which is fortunate, really.  They'd be difficult
to like."
		-- Avon</description>
    </group>

    <group id="10">
      <name>name10</name>
      <description>(10) If you're like most homeowners, you're afraid that many repairs
around your home are too difficult to tackle.  So, when your furnace
explodes, you call in a so-called professional to fix it.  The
"professional" arrives in a truck with lettering on the sides and deposits a
large quantity of tools and two assistants who spend the better part of the
week in your basement whacking objects at random with heavy wrenches, after
which the "professional" returns and gives you a bill for slightly more
money than it would cost you to run a successful campaign for the U.S.
Senate.
	And that's why you've decided to start doing things yourself. You
figure, "If those guys can fix my furnace, then so can I.  How difficult can
it be?"
	Very difficult.  In fact, most home projects are impossible, which
is why you should do them yourself.  There is no point in paying other
people to screw things up when you can easily screw them up yourself for far
less money.  This article can help you.
		-- Dave Barry, "The Taming of the Screw"</description>
    </group>

    <group id="11">
      <name>name11</name>
      <description>(11) Please stand for the National Anthem:

	Australians all, let us rejoice,
	For we are young and free.
	We've golden soil and wealth for toil
	Our home is girt by sea.
	Our land abounds in nature's gifts
	Of beauty rich and rare.
	In history's page, let every stage
	Advance Australia Fair.
	In joyful strains then let us sing,
	Advance Australia Fair.

Thank you.  You may resume your seat.</description>
    </group>

    <group id="12">
      <name>name12</name>
      <description>(12) Being a mime means never having to say you're sorry.</description>
    </group>

    <group id="13">
      <name>name13</name>
      <description>(13) :SIG: /sig/ /n./  (also common as a prefix in combining forms)
   A Special Interest Group, in one of several technical areas,
   sponsored by the Association for Computing Machinery; well-known
   ones include SIGPLAN (the Special Interest Group on Programming
   Languages), SIGARCH (the Special Interest Group for Computer
   Architecture) and SIGGRAPH (the Special Interest Group for Computer
   Graphics).  Hackers, not surprisingly, like to overextend this
   naming convention to less formal associations like SIGBEER (at ACM
   conferences) and SIGFOOD (at University of Illinois).</description>
    </group>

    <group id="14">
      <name>name14</name>
      <description>(14) :furrfu: // /excl./  [Usenet] Written-only equivalent of
   "Sheesh!"; it is, in fact, "sheesh" modified by {rot13}.
   Evolved in mid-1992 as a response to notably silly postings
   repeating urban myths on the Usenet newsgroup
   alt.folklore.urban, after some posters complained that
   "Sheesh!" as a response to {newbie}s was being overused.  See
   also {FOAF}.</description>
    </group>

    <group id="15">
      <name>name15</name>
      <description>(15) Consider the postage stamp: its usefulness consists in the ability to
stick to one thing till it gets there.
		-- Josh Billings</description>
    </group>

    <group id="16">
      <name>name16</name>
      <description>(16) Anything that is good and useful is made of chocolate.</description>
    </group>

    <group id="17">
      <name>name17</name>
      <description>(17) We wish you a Hare Krishna
We wish you a Hare Krishna
We wish you a Hare Krishna
And a Sun Myung Moon!
		-- Maxwell Smart</description>
    </group>

    <group id="18">
      <name>name18</name>
      <description>(18) :mega-: /me'g*/ /pref./ [SI] See {{quantifiers}}.</description>
    </group>

    <group id="19">
      <name>name19</name>
      <description>(19) It is only people of small moral stature who have to stand on their
dignity.</description>
    </group>

    <group id="20">
      <name>name20</name>
      <description>(20) :peek: /n.,vt./  (and {poke}) The commands in most
   microcomputer BASICs for directly accessing memory contents at an
   absolute address; often extended to mean the corresponding
   constructs in any {HLL} (peek reads memory, poke modifies it).
   Much hacking on small, non-MMU micros consists of `peek'ing
   around memory, more or less at random, to find the location where
   the system keeps interesting stuff.  Long (and variably accurate)
   lists of such addresses for various computers circulate (see
   {{interrupt list, the}}).  The results of `poke's at these
   addresses may be highly useful, mildly amusing, useless but neat,
   or (most likely) total {lossage} (see {killer poke}).

   Since a {real operating system} provides useful, higher-level
   services for the tasks commonly performed with peeks and pokes on
   micros, and real languages tend not to encourage low-level memory
   groveling, a question like "How do I do a peek in C?" is
   diagnostic of the {newbie}.  (Of course, OS kernels often have to
   do exactly this; a real C hacker would unhesitatingly, if
   unportably, assign an absolute address to a pointer variable and
   indirect through it.)</description>
    </group>

    <group id="21">
      <name>name21</name>
      <description>(21) [Norm returns from the hospital.]

Coach:  What's up, Norm?
Norm:   Everything that's supposed to be.
		-- Cheers, Diane Meets Mom

Sam:  What's new, Normie?
Norm: Terrorists, Sam.  They've taken over my stomach.  They're demanding beer.
		-- Cheers, The Heart is a Lonely Snipehunter

Coach: What'll it be, Normie?
Norm:  Just the usual, Coach.  I'll have a froth of beer and a snorkel.
		-- Cheers, King of the Hill</description>
    </group>

    <group id="22">
      <name>name22</name>
      <description>(22) I just need enough to tide me over until I need more.
		-- Bill Hoest</description>
    </group>

    <group id="23">
      <name>name23</name>
      <description>(23) ___====-_  _-====___
	      _--~~~#####//      \\#####~~~--_
	   _-~##########// (    ) \\##########~-_
	  -############//  :\^^/:  \\############-
	_~############//   (@::@)   \\############~_
       ~#############((     \\//     ))#############~
      -###############\\    (^^)    //###############-
     -#################\\  / "" \  //#################-
    -###################\\/      \//###################-
   _#/:##########/\######(   /\   )######/\##########:\#_
   :/ :#/\#/\#/\/  \#/\##\  :  :  /##/\#/  \/\#/\#/\#: \:
   "  :/  V  V  "   V  \#\: :  : :/#/  V   "  V  V  \:  "
      "   "  "      "   \ : :  : : /   "      "  "   "</description>
    </group>

    <group id="24">
      <name>name24</name>
      <description>(24) Bore, n:
	A person who talks when you wish him to listen.
		-- Ambrose Bierce</description>
    </group>

    <group id="25">
      <name>name25</name>
      <description>(25) THE LESSER-KNOWN PROGRAMMING LANGUAGES #10: SIMPLE

SIMPLE is an acronym for Sheer Idiot's Monopurpose Programming Language
Environment.  This language, developed at the Hanover College for
Technological Misfits, was designed to make it impossible to write code
with errors in it.  The statements are, therefore, confined to BEGIN,
END and STOP.  No matter how you arrange the statements, you can't make
a syntax error.  Programs written in SIMPLE do nothing useful.  Thus
they achieve the results of programs written in other languages without
the tedious, frustrating process of testing and debugging.</description>
    </group>

    <group id="26">
      <name>name26</name>
      <description>(26) A friend of mine is into Voodoo Acupuncture.  You don't have to go.
You'll just be walking down the street and...  Ooohh, that's much better.
		-- Steven Wright</description>
    </group>

    <group id="27">
      <name>name27</name>
      <description>(27) You know it's going to be a long day when you get up, shave and shower,
start to get dressed and your shoes are still warm.
		-- Dean Webber</description>
    </group>

    <group id="28">
      <name>name28</name>
      <description>(28) Come live with me, and be my love,
