<?xml version='1.0' encoding='ISO-8859-1' ?>
<!DOCTYPE  matieres [
<!ELEMENT matieres (matiere*)>
<!ELEMENT matiere (nom)>
<!ATTLIST matiere id  ID   #REQUIRED>
<!ELEMENT nom  (#PCDATA)>
]>

<matieres>
	<matiere id="1">
		<nom>L3/INF1</nom>
	</matiere>
	<matiere id="2">
		<nom>L3/INF2</nom>
	</matiere>
	<matiere id="3">
		<nom>L3/INF3</nom>
	</matiere>
	<matiere id="4">
		<nom>L3/INF4</nom>
	</matiere>
	<matiere id="5">
		<nom>L3/INF5</nom>
	</matiere>
	<matiere id="6">
		<nom>L3/INF6</nom>
	</matiere>
	<matiere id="7">
		<nom>L3/INF7</nom>
	</matiere>	
	<matiere id="8">
		<nom>L3/ISI1</nom>
	</matiere>
	<matiere id="9">
		<nom>L3/ISI2</nom>
	</matiere>
	<matiere id="10">
		<nom>L3/ISI3</nom>
	</matiere>
	<matiere id="11">
		<nom>L3/ISI4</nom>
	</matiere>
	<matiere id="12">
		<nom>L3/ISI5</nom>
	</matiere>	
	<matiere id="13">
		<nom>L3/TC1</nom>
	</matiere>
	<matiere id="14">
		<nom>L3/AN1</nom>
	</matiere>
	<matiere id="15">
		<nom>L3/MM1</nom>
	</matiere>
	<matiere id="16">
		<nom>L3/MM2</nom>
	</matiere>	
	<matiere id="17">
		<nom>L3/MM3</nom>
	</matiere>
	<matiere id="18">
		<nom>L3/MM4</nom>
	</matiere>	
	<matiere id="19">
		<nom>L3/GO1</nom>
	</matiere>
	<matiere id="20">
		<nom>L3/GO2</nom>
	</matiere>
	<matiere id="21">
		<nom>L3/GO3</nom>
	</matiere>
	<matiere id="22">
		<nom>L3/PROD1</nom>
	</matiere>
	<matiere id="23">
		<nom>L3/PROD2</nom>
	</matiere>	
	
	<matiere id="24">
		<nom>M1/INF1</nom>
	</matiere>
	<matiere id="25">
		<nom>M1/INF2</nom>
	</matiere>
	<matiere id="26">
		<nom>M1/INF3</nom>
	</matiere>
	<matiere id="27">
		<nom>M1/INF4</nom>
	</matiere>
	<matiere id="28">
		<nom>M1/INF5</nom>
	</matiere>
	<matiere id="29">
		<nom>M1/INF6</nom>
	</matiere>
	<matiere id="30">
		<nom>M1/INF7</nom>
	</matiere>	
	<matiere id="31">
		<nom>M1/ISI1</nom>
	</matiere>
	<matiere id="32">
		<nom>M1/ISI2</nom>
	</matiere>
	<matiere id="33">
		<nom>M1/ISI3</nom>
	</matiere>
	<matiere id="34">
		<nom>M1/ISI4</nom>
	</matiere>	
	<matiere id="35">
		<nom>M1/TC1</nom>
	</matiere>
	<matiere id="36">
		<nom>M1/AN1</nom>
	</matiere>
	<matiere id="37">
		<nom>M1/MM1</nom>
	</matiere>
	<matiere id="38">
		<nom>M1/MM2</nom>
	</matiere>	
	<matiere id="39">
		<nom>M1/MM3</nom>
	</matiere>	
	<matiere id="40">
		<nom>M1/GO1</nom>
	</matiere>
	<matiere id="41">
		<nom>M1/GO2</nom>
	</matiere>
	<matiere id="42">
		<nom>M1/GO3</nom>
	</matiere>
	<matiere id="43">
		<nom>M1/PROD1</nom>
	</matiere>
	<matiere id="44">
		<nom>M1/PROD2</nom>
	</matiere>
	
	
	<matiere id="45">
		<nom>M2/INF1</nom>
	</matiere>
	<matiere id="46">
		<nom>M2/INF2</nom>
	</matiere>
	<matiere id="47">
		<nom>M2/INF3</nom>
	</matiere>
	<matiere id="48">
		<nom>M2/INF4</nom>
	</matiere>
	<matiere id="49">
		<nom>M2/ISI1</nom>
	</matiere>
	<matiere id="50">
		<nom>M2/ISI2</nom>
	</matiere>
	<matiere id="51">
		<nom>M2/ISI3</nom>
	</matiere>
	<matiere id="52">
		<nom>M2/GO1</nom>
	</matiere>
	<matiere id="53">
		<nom>M2/GO2</nom>
	</matiere>
	<matiere id="54">
		<nom>M2/MM1</nom>
	</matiere>
	<matiere id="55">
		<nom>M2/PROD1</nom>
	</matiere>
	<matiere id="56">
		<nom>M2/PROD3</nom>
	</matiere>
	<matiere id="57">
		<nom>M2/TC1</nom>
	</matiere>
</matieres>
