<?xml version='1.0' encoding='ISO-8859-1' ?>
<!DOCTYPE  seances [
<!ELEMENT seances (seance*)>

<!ELEMENT seance (date)>
<!ATTLIST seance refmat  IDREF  #REQUIRED>
<!ATTLIST seance refprom  IDREF  #REQUIRED>
<!ATTLIST seance refsal  IDREF  #REQUIRED>

<!ELEMENT date (datedebut,datefin)>
<!ELEMENT datedebut  (#PCDATA)>
<!ELEMENT datefin  (#PCDATA)>
]>


<seances>
	<seance refmat="24" refprom="02" refsal="C1408">
		<date>
			<datedebut>21/09/10 9:30:00</datedebut>
			<datefin>21/09/10 12:30:00</datefin>
		</date>
	</seance>
	<seance refmat="24" refprom="02" refsal="C1408">
		<date>
			<datedebut>21/09/10 14:00:00</datedebut>
			<datefin>21/09/10 17:00:00</datefin>
		</date>
	</seance>
	<seance refmat="24" refprom="02" refsal="C1408">
		<date>
			<datedebut>23/09/10 9:30:00</datedebut>
			<datefin>23/09/10 12:30:00</datefin>
		</date>
	</seance>
	<seance refmat="24" refprom="02" refsal="C1408">
		<date>
			<datedebut>07/10/10 9:30:00</datedebut>
			<datefin>07/10/10 12:30:00</datefin>
		</date>
	</seance>
	<seance refmat="24" refprom="02" refsal="C1408">
		<date>
			<datedebut>07/10/10 14:00:00</datedebut>
			<datefin>07/10/10 17:00:00</datefin>
		</date>
	</seance>
	<seance refmat="24" refprom="02" refsal="C1408">
		<date>
			<datedebut>14/10/10 14:00:00</datedebut>
			<datefin>14/10/10 17:00:00</datefin>
		</date>
	</seance>
	<seance refmat="24" refprom="02" refsal="C1408">
		<date>
			<datedebut>21/10/10 14:00:00</datedebut>
			<datefin>21/10/10 17:00:00</datefin>
		</date>
	</seance>
	<seance refmat="24" refprom="02" refsal="C1408">
		<date>
			<datedebut>28/10/10 14:00:00</datedebut>
			<datefin>28/10/10 17:00:00</datefin>
		</date>
	</seance>
	<seance refmat="24" refprom="02" refsal="C1408">
		<date>
			<datedebut>04/11/10 14:00:00</datedebut>
			<datefin>04/11/10 17:00:00</datefin>
		</date>
	</seance>
	<seance refmat="24" refprom="02" refsal="C1408">
		<date>
			<datedebut>18/11/10 14:00:00</datedebut>
			<datefin>18/11/10 17:00:00</datefin>
		</date>
	</seance>
	<seance refmat="24" refprom="02" refsal="C1408">
		<date>
			<datedebut>25/11/10 14:00:00</datedebut>
			<datefin>25/11/10 17:00:00</datefin>
		</date>
	</seance>
	<seance refmat="24" refprom="02" refsal="C1408">
		<date>
			<datedebut>02/12/10 14:00:00</datedebut>
			<datefin>02/12/10 17:00:00</datefin>
		</date>
	</seance>

	<seance refmat="31" refprom="02" refsal="C1408">
		<date>
			<datedebut>24/09/10 09:00:00</datedebut>
			<datefin>24/09/10 12:00:00</datefin>
		</date>
	</seance>
	<seance refmat="31" refprom="02" refsal="C1408">
		<date>
			<datedebut>24/09/10 14:00:00</datedebut>
			<datefin>24/09/10 17:00:00</datefin>
		</date>
	</seance>
	<seance refmat="31" refprom="02" refsal="C1408">
		<date>
			<datedebut>28/09/10 09:30:00</datedebut>
			<datefin>28/09/10 12:30:00</datefin>
		</date>
	</seance>
	<seance refmat="31" refprom="02" refsal="C1408">
		<date>
			<datedebut>28/09/10 14:00:00</datedebut>
			<datefin>28/09/10 17:00:00</datefin>
		</date>
	</seance>
	<seance refmat="31" refprom="02" refsal="C1408">
		<date>
			<datedebut>05/10/10 09:30:00</datedebut>
			<datefin>05/10/10 12:30:00</datefin>
		</date>
	</seance>
	<seance refmat="31" refprom="02" refsal="C1408">
		<date>
			<datedebut>05/10/10 14:00:00</datedebut>
			<datefin>05/10/10 17:00:00</datefin>
		</date>
	</seance>
	<seance refmat="31" refprom="02" refsal="C1408">
		<date>
			<datedebut>15/10/10 09:30:00</datedebut>
			<datefin>15/10/10 12:30:00</datefin>
		</date>
	</seance>
	<seance refmat="31" refprom="02" refsal="C1408">
		<date>
			<datedebut>15/10/10 14:00:00</datedebut>
			<datefin>15/10/10 17:00:00</datefin>
		</date>
	</seance>
	<seance refmat="31" refprom="02" refsal="C1408">
		<date>
			<datedebut>19/10/10 14:00:00</datedebut>
			<datefin>19/10/10 17:00:00</datefin>
		</date>
	</seance>
	<seance refmat="31" refprom="02" refsal="C1408">
		<date>
			<datedebut>22/10/10 09:30:00</datedebut>
			<datefin>22/10/10 12:30:00</datefin>
		</date>
	</seance>
	<seance refmat="31" refprom="02" refsal="C1408">
		<date>
			<datedebut>02/11/10 14:00:00</datedebut>
			<datefin>02/11/10 17:00:00</datefin>
		</date>
	</seance>
	<seance refmat="31" refprom="02" refsal="C1408">
		<date>
			<datedebut>05/11/10 14:00:00</datedebut>
			<datefin>05/11/10 17:00:00</datefin>
		</date>
	</seance>
	<seance refmat="31" refprom="02" refsal="C1408">
		<date>
			<datedebut>09/11/10 14:00:00</datedebut>
			<datefin>09/11/10 17:00:00</datefin>
		</date>
	</seance>
	<seance refmat="31" refprom="02" refsal="C1408">
		<date>
			<datedebut>16/11/10 14:00:00</datedebut>
			<datefin>16/11/10 17:00:00</datefin>
		</date>
	</seance>
	<seance refmat="31" refprom="02" refsal="C1408">
		<date>
			<datedebut>03/12/10 14:00:00</datedebut>
			<datefin>03/12/10 17:00:00</datefin>
		</date>
	</seance>
	<seance refmat="31" refprom="02" refsal="C1408">
		<date>
			<datedebut>09/12/10 14:00:00</datedebut>
			<datefin>09/12/10 17:00:00</datefin>
		</date>
	</seance>
	<seance refmat="31" refprom="02" refsal="C1408">
		<date>
			<datedebut>10/12/10 14:00:00</datedebut>
			<datefin>10/12/10 16:00:00</datefin>
		</date>
	</seance>
	<seance refmat="31" refprom="02" refsal="C1408">
		<date>
			<datedebut>14/12/10 13:00:00</datedebut>
			<datefin>14/12/10 17:00:00</datefin>
		</date>
	</seance>
	<seance refmat="31" refprom="02" refsal="C1408">
		<date>
			<datedebut>03/01/2011 9:30:00</datedebut>
			<datefin>03/01/2011 12:30:00</datefin>
		</date>
	</seance>
	<seance refmat="31" refprom="02" refsal="C1408">
		<date>
			<datedebut>03/01/2011 14:00:00</datedebut>
			<datefin>03/01/2011 17:00:00</datefin>
		</date>
	</seance>
	
	<seance refmat="25" refprom="02" refsal="C1408">
		<date>
			<datedebut>27/09/10 09:00:00</datedebut>
			<datefin>27/09/10 12:00:00</datefin>
		</date>
	</seance>
	<seance refmat="25" refprom="02" refsal="C1408">
		<date>
			<datedebut>27/09/10 14:00:00</datedebut>
			<datefin>27/09/10 17:00:00</datefin>
		</date>
	</seance>
	<seance refmat="25" refprom="02" refsal="C1408">
		<date>
			<datedebut>30/09/10 09:00:00</datedebut>
			<datefin>30/09/10 12:00:00</datefin>
		</date>
	</seance>
	<seance refmat="25" refprom="02" refsal="C1408">
		<date>
			<datedebut>30/09/10 14:00:00</datedebut>
			<datefin>30/09/10 17:00:00</datefin>
		</date>
	</seance>
	<seance refmat="25" refprom="02" refsal="C1408">
		<date>
			<datedebut>01/10/10 09:00:00</datedebut>
			<datefin>01/10/10 12:00:00</datefin>
		</date>
	</seance>
	<seance refmat="25" refprom="02" refsal="C1408">
		<date>
			<datedebut>01/10/10 14:00:00</datedebut>
			<datefin>01/10/10 17:00:00</datefin>
		</date>
	</seance>
	<seance refmat="25" refprom="02" refsal="C1408">
		<date>
			<datedebut>04/10/10 09:00:00</datedebut>
			<datefin>04/10/10 12:00:00</datefin>
		</date>
	</seance>
	<seance refmat="25" refprom="02" refsal="C1408">
		<date>
			<datedebut>04/10/10 14:00:00</datedebut>
			<datefin>04/10/10 17:00:00</datefin>
		</date>
	</seance>
	<seance refmat="25" refprom="02" refsal="C1408">
		<date>
			<datedebut>08/10/10 09:00:00</datedebut>
			<datefin>08/10/10 12:00:00</datefin>
		</date>
	</seance>
	<seance refmat="25" refprom="02" refsal="C1408">
		<date>
			<datedebut>08/10/10 14:00:00</datedebut>
			<datefin>08/10/10 17:00:00</datefin>
		</date>
	</seance>
	<seance refmat="25" refprom="02" refsal="C1408">
		<date>
			<datedebut>26/10/10 14:00:00</datedebut>
			<datefin>26/10/10 17:00:00</datefin>
		</date>
	</seance>
	<seance refmat="25" refprom="02" refsal="C1408">
		<date>
			<datedebut>26/10/10 14:00:00</datedebut>
			<datefin>26/10/10 17:00:00</datefin>
		</date>
	</seance>
	<seance refmat="25" refprom="02" refsal="C1408">
		<date>
			<datedebut>29/10/10 09:00:00</datedebut>
			<datefin>29/10/10 12:00:00</datefin>
		</date>
	</seance>
	<seance refmat="25" refprom="02" refsal="C1408">
		<date>
			<datedebut>29/10/10 14:00:00</datedebut>
			<datefin>29/10/10 17:00:00</datefin>
		</date>
	</seance>
	<seance refmat="25" refprom="02" refsal="C1408">
		<date>
			<datedebut>19/11/10 14:00:00</datedebut>
			<datefin>19/11/10 17:00:00</datefin>
		</date>
	</seance>
	<seance refmat="25" refprom="02" refsal="C1408">
		<date>
			<datedebut>19/11/10 14:00:00</datedebut>
			<datefin>19/11/10 17:00:00</datefin>
		</date>
	</seance>
	<seance refmat="25" refprom="02" refsal="C1408">
		<date>
			<datedebut>26/11/10 14:00:00</datedebut>
			<datefin>26/11/10 17:00:00</datefin>
		</date>
	</seance>
	<seance refmat="25" refprom="02" refsal="C1408">
		<date>
			<datedebut>26/11/10 14:00:00</datedebut>
			<datefin>26/11/10 17:00:00</datefin>
		</date>
	</seance>
	
	<seance refmat="36" refprom="02" refsal="C1408">
		<date>
			<datedebut>06/10/10 09:00:00</datedebut>
			<datefin>06/10/10 12:00:00</datefin>
		</date>
	</seance>
	<seance refmat="36" refprom="02" refsal="C1408">
		<date>
			<datedebut>06/10/10 13:00:00</datedebut>
			<datefin>06/10/10 16:00:00</datefin>
		</date>
	</seance>
	<seance refmat="36" refprom="02" refsal="C1408">
		<date>
			<datedebut>12/10/10 09:00:00</datedebut>
			<datefin>12/10/10 12:00:00</datefin>
		</date>
	</seance>
	<seance refmat="36" refprom="02" refsal="C1408">
		<date>
			<datedebut>26/10/10 09:00:00</datedebut>
			<datefin>26/10/10 12:00:00</datefin>
		</date>
	</seance>
	<seance refmat="36" refprom="02" refsal="C1408">
		<date>
			<datedebut>02/11/10 09:00:00</datedebut>
			<datefin>02/11/10 12:00:00</datefin>
		</date>
	</seance>
	<seance refmat="36" refprom="02" refsal="C1408">
		<date>
			<datedebut>09/11/10 09:00:00</datedebut>
			<datefin>09/11/10 12:00:00</datefin>
		</date>
	</seance>
	<seance refmat="36" refprom="02" refsal="C1408">
		<date>
			<datedebut>16/11/10 09:00:00</datedebut>
			<datefin>16/11/10 12:00:00</datefin>
		</date>
	</seance>
	<seance refmat="36" refprom="02" refsal="C1408">
		<date>
			<datedebut>23/11/10 09:00:00</datedebut>
			<datefin>23/11/10 12:00:00</datefin>
		</date>
	</seance>
	<seance refmat="36" refprom="02" refsal="C1408">
		<date>
			<datedebut>30/11/10 09:00:00</datedebut>
			<datefin>30/11/10 12:00:00</datefin>
		</date>
	</seance>
	<seance refmat="36" refprom="02" refsal="C1408">
		<date>
			<datedebut>07/12/10 09:00:00</datedebut>
			<datefin>07/12/10 12:00:00</datefin>
		</date>
	</seance>
	<seance refmat="36" refprom="02" refsal="C1408">
		<date>
			<datedebut>14/12/10 09:00:00</datedebut>
			<datefin>14/12/10 12:00:00</datefin>
		</date>
	</seance>
	
	<seance refmat="35" refprom="02" refsal="C1408">
		<date>
			<datedebut>13/10/10 09:30:00</datedebut>
			<datefin>13/10/10 12:30:00</datefin>
		</date>
	</seance>
	
	<seance refmat="35" refprom="02" refsal="C1408">
		<date>
			<datedebut>27/10/10 09:30:00</datedebut>
			<datefin>27/10/10 12:30:00</datefin>
		</date>
	</seance>
	
	<seance refmat="35" refprom="02" refsal="C1408">
		<date>
			<datedebut>03/11/10 09:30:00</datedebut>
			<datefin>01/11/10 12:30:00</datefin>
		</date>
	</seance>
	
	<seance refmat="35" refprom="02" refsal="C1408">
		<date>
			<datedebut>17/11/10 09:30:00</datedebut>
			<datefin>17/11/10 12:30:00</datefin>
		</date>
	</seance>
	
	<seance refmat="35" refprom="02" refsal="C1408">
		<date>
			<datedebut>24/11/10 09:30:00</datedebut>
			<datefin>24/11/10 12:30:00</datefin>
		</date>
	</seance>
	<seance refmat="35" refprom="02" refsal="C1408">
		<date>
			<datedebut>07/01/11 09:30:00</datedebut>
			<datefin>07/01/11 12:30:00</datefin>
		</date>
	</seance>
	<seance refmat="35" refprom="02" refsal="C1408">
		<date>
			<datedebut>07/01/11 14:00:00</datedebut>
			<datefin>07/01/11 17:00:00</datefin>
		</date>
	</seance>
	<seance refmat="35" refprom="02" refsal="C1408">
		<date>
			<datedebut>10/01/11 09:30:00</datedebut>
			<datefin>10/01/11 12:30:00</datefin>
		</date>
	</seance>
	<seance refmat="35" refprom="02" refsal="C1408">
		<date>
			<datedebut>10/01/11 14:00:00</datedebut>
			<datefin>10/01/11 17:00:00</datefin>
		</date>
	</seance>
	<seance refmat="35" refprom="02" refsal="C1408">
		<date>
			<datedebut>13/01/11 14:00:00</datedebut>
			<datefin>13/01/11 17:00:00</datefin>
		</date>
	</seance>
	
	<seance refmat="38" refprom="02" refsal="Amphi L">
		<date>
			<datedebut>04/10/10 17:00:00</datedebut>
			<datefin>04/10/10 18:30:00</datefin>
		</date>
	</seance>
	<seance refmat="38" refprom="02" refsal="C1501">
		<date>
			<datedebut>13/10/10 14:30:00</datedebut>
			<datefin>13/10/10 16:30:00</datefin>
		</date>
	</seance>
	<seance refmat="38" refprom="02" refsal="Amphi J">
		<date>
			<datedebut>13/10/10 17:00:00</datedebut>
			<datefin>13/10/10 18:30:00</datefin>
		</date>
	</seance>
	
	<seance refmat="38" refprom="02" refsal="C1501">
		<date>
			<datedebut>20/10/10 14:30:00</datedebut>
			<datefin>20/10/10 16:30:00</datefin>
		</date>
	</seance>	
	<seance refmat="38" refprom="02" refsal="Amphi J">
		<date>
			<datedebut>20/10/10 17:00:00</datedebut>
			<datefin>20/10/10 18:30:00</datefin>
		</date>
	</seance>
	<seance refmat="38" refprom="02" refsal="C1501">
		<date>
			<datedebut>27/10/10 14:30:00</datedebut>
			<datefin>27/10/10 16:30:00</datefin>
		</date>
	</seance>	
	<seance refmat="38" refprom="02" refsal="Amphi J">
		<date>
			<datedebut>27/10/10 17:00:00</datedebut>
			<datefin>27/10/10 18:30:00</datefin>
		</date>
	</seance>
	<seance refmat="38" refprom="02" refsal="C1501">
		<date>
			<datedebut>03/11/10 14:30:00</datedebut>
			<datefin>03/11/10 16:30:00</datefin>
		</date>
	</seance>	
	<seance refmat="38" refprom="02" refsal="Amphi J">
		<date>
			<datedebut>03/11/10 17:00:00</datedebut>
			<datefin>03/11/10 18:30:00</datefin>
		</date>
	</seance>
	<seance refmat="38" refprom="02" refsal="C1501">
		<date>
			<datedebut>17/11/10 14:30:00</datedebut>
			<datefin>17/11/10 16:30:00</datefin>
		</date>
	</seance>	
	<seance refmat="38" refprom="02" refsal="Amphi J">
		<date>
			<datedebut>17/11/10 17:00:00</datedebut>
			<datefin>17/11/10 18:30:00</datefin>
		</date>
	</seance>
	<seance refmat="38" refprom="02" refsal="C1501">
		<date>
			<datedebut>24/11/10 14:30:00</datedebut>
			<datefin>24/11/10 16:30:00</datefin>
		</date>
	</seance>	
	<seance refmat="38" refprom="02" refsal="Amphi J">
		<date>
			<datedebut>24/11/10 17:00:00</datedebut>
			<datefin>24/11/10 18:30:00</datefin>
		</date>
	</seance>
	<seance refmat="38" refprom="02" refsal="C1501">
		<date>
			<datedebut>01/12/10 14:30:00</datedebut>
			<datefin>01/12/10 16:30:00</datefin>
		</date>
	</seance>	
	<seance refmat="38" refprom="02" refsal="Amphi J">
		<date>
			<datedebut>01/12/10 17:00:00</datedebut>
			<datefin>01/12/10 18:30:00</datefin>
		</date>
	</seance>
	<seance refmat="38" refprom="02" refsal="C1501">
		<date>
			<datedebut>01/12/10 14:30:00</datedebut>
			<datefin>01/12/10 16:30:00</datefin>
		</date>
	</seance>	
	<seance refmat="38" refprom="02" refsal="Amphi J">
		<date>
			<datedebut>01/12/10 17:00:00</datedebut>
			<datefin>01/12/10 18:30:00</datefin>
		</date>
	</seance>
	<seance refmat="38" refprom="02" refsal="C1501">
		<date>
			<datedebut>08/12/10 14:30:00</datedebut>
			<datefin>08/12/10 16:30:00</datefin>
		</date>
	</seance>	
	<seance refmat="38" refprom="02" refsal="Amphi J">
		<date>
			<datedebut>08/12/10 17:00:00</datedebut>
			<datefin>08/12/10 18:30:00</datefin>
		</date>
	</seance>
	<seance refmat="38" refprom="02" refsal="C1501">
		<date>
			<datedebut>15/12/10 14:30:00</datedebut>
			<datefin>15/12/10 16:30:00</datefin>
		</date>
	</seance>	
	<seance refmat="38" refprom="02" refsal="Amphi J">
		<date>
			<datedebut>15/12/10 17:00:00</datedebut>
			<datefin>15/12/10 18:30:00</datefin>
		</date>
	</seance>
	
	
	<seance refmat="34" refprom="02" refsal="C1408">
		<date>
			<datedebut>14/10/10 09:30:00</datedebut>
			<datefin>14/10/10 12:30:00</datefin>
		</date>
	</seance>
	
	<seance refmat="34" refprom="02" refsal="C1408">
		<date>
			<datedebut>21/10/10 09:30:00</datedebut>
			<datefin>21/10/10 12:30:00</datefin>
		</date>
	</seance>
	
	
	<seance refmat="34" refprom="02" refsal="C1408">
		<date>
			<datedebut>28/10/10 09:30:00</datedebut>
			<datefin>28/10/10 12:30:00</datefin>
		</date>
	</seance>
	
	
	<seance refmat="34" refprom="02" refsal="C1408">
		<date>
			<datedebut>04/11/10 09:30:00</datedebut>
			<datefin>04/11/10 12:30:00</datefin>
		</date>
	</seance>
	
	<seance refmat="34" refprom="02" refsal="C1408">
		<date>
			<datedebut>18/11/10 09:30:00</datedebut>
			<datefin>18/11/10 12:30:00</datefin>
		</date>
	</seance>
	
	<seance refmat="34" refprom="02" refsal="C1408">
		<date>
			<datedebut>25/11/10 09:30:00</datedebut>
			<datefin>25/11/10 12:30:00</datefin>
		</date>
	</seance>
	
	
	<seance refmat="34" refprom="02" refsal="C1408">
		<date>
			<datedebut>02/12/10 09:30:00</datedebut>
			<datefin>02/12/10 12:30:00</datefin>
		</date>
	</seance>
	<seance refmat="34" refprom="02" refsal="C1408">
		<date>
			<datedebut>09/12/10 09:30:00</datedebut>
			<datefin>09/12/10 12:30:00</datefin>
		</date>
	</seance>
	<seance refmat="34" refprom="02" refsal="C1408">
		<date>
			<datedebut>16/12/10 09:30:00</datedebut>
			<datefin>16/12/10 12:30:00</datefin>
		</date>
	</seance>
	<seance refmat="34" refprom="02" refsal="C1408">
		<date>
			<datedebut>06/01/11 09:30:00</datedebut>
			<datefin>06/01/11 12:30:00</datefin>
		</date>
	</seance>
	
	<seance refmat="37" refprom="02" refsal="C1408">
		<date>
			<datedebut>11/10/10 14:00:00</datedebut>
			<datefin>11/10/10 17:00:00</datefin>
		</date>
	</seance>
	<seance refmat="37" refprom="02" refsal="C1408">
		<date>
			<datedebut>18/10/10 14:00:00</datedebut>
			<datefin>18/10/10 17:00:00</datefin>
		</date>
	</seance>
	<seance refmat="37" refprom="02" refsal="C1408">
		<date>
			<datedebut>25/10/10 14:00:00</datedebut>
			<datefin>25/10/10 17:00:00</datefin>
		</date>
	</seance>
	<seance refmat="37" refprom="02" refsal="C1408">
		<date>
			<datedebut>08/11/10 14:00:00</datedebut>
			<datefin>08/11/10 17:00:00</datefin>
		</date>
	</seance>
	<seance refmat="37" refprom="02" refsal="C1408">
		<date>
			<datedebut>15/11/10 14:00:00</datedebut>
			<datefin>15/11/10 17:00:00</datefin>
		</date>
	</seance>
	<seance refmat="37" refprom="02" refsal="C1408">
		<date>
			<datedebut>22/11/10 14:00:00</datedebut>
			<datefin>22/11/10 17:00:00</datefin>
		</date>
	</seance>
	<seance refmat="37" refprom="02" refsal="C1408">
		<date>
			<datedebut>29/11/10 14:00:00</datedebut>
			<datefin>29/11/10 17:00:00</datefin>
		</date>
	</seance>
	<seance refmat="37" refprom="02" refsal="C1408">
		<date>
			<datedebut>06/12/10 14:00:00</datedebut>
			<datefin>06/12/10 17:00:00</datefin>
		</date>
	</seance>
	<seance refmat="37" refprom="02" refsal="C1408">
		<date>
			<datedebut>13/12/10 14:00:00</datedebut>
			<datefin>13/12/10 17:00:00</datefin>
		</date>
	</seance>
	
	<seance refmat="40" refprom="02" refsal="C1408">
		<date>
			<datedebut>05/11/10 09:00:00</datedebut>
			<datefin>05/11/10 13:00:00</datefin>
		</date>
	</seance>
	<seance refmat="40" refprom="02" refsal="C1408">
		<date>
			<datedebut>12/11/10 14:00:00</datedebut>
			<datefin>12/11/10 18:00:00</datefin>
		</date>
	</seance>
	<seance refmat="40" refprom="02" refsal="C1408">
		<date>
			<datedebut>23/11/10 13:00:00</datedebut>
			<datefin>23/11/10 17:00:00</datefin>
		</date>
	</seance>
	<seance refmat="40" refprom="02" refsal="C1408">
		<date>
			<datedebut>30/11/10 14:00:00</datedebut>
			<datefin>30/11/10 18:00:00</datefin>
		</date>
	</seance>
	<seance refmat="40" refprom="02" refsal="C1408">
		<date>
			<datedebut>03/12/10 09:00:00</datedebut>
			<datefin>03/12/10 13:00:00</datefin>
		</date>
	</seance>
	<seance refmat="40" refprom="02" refsal="C1408">
		<date>
			<datedebut>07/11/10 14:00:00</datedebut>
			<datefin>07/11/10 18:00:00</datefin>
		</date>
	</seance>
	<seance refmat="40" refprom="02" refsal="C1408">
		<date>
			<datedebut>10/12/10 09:00:00</datedebut>
			<datefin>10/12/10 13:00:00</datefin>
		</date>
	</seance>
	<seance refmat="40" refprom="02" refsal="C1408">
		<date>
			<datedebut>17/12/10 09:30:00</datedebut>
			<datefin>17/12/10 12:30:00</datefin>
		</date>
	</seance>
	<seance refmat="40" refprom="02" refsal="C1408">
		<date>
			<datedebut>17/12/10 13:30:00</datedebut>
			<datefin>17/12/10 16:30:00</datefin>
		</date>
	</seance>
	<seance refmat="40" refprom="02" refsal="B1302">
		<date>
			<datedebut>04/01/11 09:00:00</datedebut>
			<datefin>04/01/11 17:00:00</datefin>
		</date>
	</seance>
	<seance refmat="40" refprom="02" refsal="C1408">
		<date>
			<datedebut>11/01/11 09:00:00</datedebut>
			<datefin>11/01/11 17:00:00</datefin>
		</date>
	</seance>
	<seance refmat="40" refprom="02" refsal="C1408">
		<date>
			<datedebut>14/01/11 09:00:00</datedebut>
			<datefin>14/01/11 17:00:00</datefin>
		</date>
	</seance>
	
</seances>
